import {readFile,writeFile} from 'node:fs/promises';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import cases from '/Users/kazukikomura/Developer/secretary/research-public/src/cases.js';
import {CASES_PER_PARTICIPANT as K,SENDERS} from '/Users/kazukikomura/Developer/secretary/research-public/src/measurement.js';
const raw=await readFile('/Users/kazukikomura/Developer/secretary/research-public/src/worker.js','utf8');
const code=raw.split('async function api(')[0].replace(/^import .*$/gm,'')+'\nglobalThis.runAllocation=allocate;globalThis.orders=WILLIAMS;';
function runner(seed){let rnd=seed;const context={cases,K,SENDERS,TextEncoder,crypto:{getRandomValues(a){a[0]=createHash('sha256').update(seed+':'+rnd++).digest().readUInt32LE(0);return a;}}};vm.createContext(context);vm.runInContext(code,context);const saved=[];const env={DB:{prepare(sql){return {bind(mode){return {async all(){const m=new Map();if(sql.startsWith('SELECT sequence')){for(const p of saved)m.set(p.sequence,(m.get(p.sequence)||0)+1);return {results:[...m].map(([sequence,n])=>({sequence,n}))};}for(const p of saved)for(const c of p.cases){const value={case_id:c.case_id,base_id:c.base_id,idx:c.idx,condition:c.condition,disclosure:p.disclosure};const k=JSON.stringify(value);const item=m.get(k)||{...value,n:0};item.n++;m.set(k,item);}return {results:[...m.values()]};}};}};}}};return {context,saved,allocate:()=>context.runAllocation(env,'live')};}
function summarize(saved){const seq=Array(8).fill(0),disclosure={},themes={},cells={};for(const p of saved){seq[p.sequence]++;disclosure[p.disclosure]=(disclosure[p.disclosure]||0)+1;if(p.cases.length!==4||new Set(p.cases.map(c=>c.case_id)).size!==4||new Set(p.cases.map(c=>c.condition)).size!==4)throw Error('invalid plan');for(const c of p.cases){themes[c.case_id]=(themes[c.case_id]||0)+1;const key=[p.disclosure,c.case_id,c.condition].join('|');cells[key]=(cells[key]||0)+1;}}const fullCells=['disclosed','undisclosed'].flatMap(d=>cases.cases.flatMap(c=>cases.conditions.map(s=>cells[[d,c.id,s].join('|')]||0)));return {participants:saved.length,sequenceCounts:seq,disclosure,themeCounts:themes,themeConditionDisclosureCellMin:Math.min(...fullCells),themeConditionDisclosureCellMax:Math.max(...fullCells)};}
const simulations=[];for(let seed=1;seed<=20;seed++){const r=runner(seed);for(let i=0;i<50;i++)r.saved.push(await r.allocate());simulations.push({seed,...summarize(r.saved)});}
const concurrent=runner(100);const plans=await Promise.all(Array.from({length:50},()=>concurrent.allocate()));concurrent.saved.push(...plans);
const orders=runner(1).context.orders;const adjacent=orders.flatMap(row=>row.slice(0,-1).map((v,i)=>v+'>'+row[i+1]));
const result={checkedAt:new Date().toISOString(),method:'Executed current allocate() in isolated VM, mock DB, deterministic PRNG replacing only crypto for reproducibility. No production writes. Concurrent scenario deliberately lets all plans read empty counts before any insert.',orders,williams:{everyStateOncePerPosition:[0,1,2,3].every(p=>new Set(orders.map(r=>r[p])).size===4),adjacentPairsUnique:new Set(adjacent).size===12},sequential:simulations,concurrentIllustration:summarize(concurrent.saved)};
await writeFile('/private/tmp/handoff-allocation-audit/simulation.json',JSON.stringify(result,null,2));
console.log(JSON.stringify({williams:result.williams,example:simulations[0],observedDisclosureSplits:[...new Set(simulations.map(s=>`${s.disclosure.disclosed}/${s.disclosure.undisclosed}`))],concurrentIllustration:result.concurrentIllustration},null,2));
