// Build src/cases.js from the manuscript's stimulus set.
// Materials (request, terms, sources, U1/U2) come from stimuli-scope-20260920 v3.
// v8: document versions and plain texts come from ./stimuli-v8 (baseline, missing_info, off_focus, source_deviation; A–D labelled request; factual MC wording).
// Participants never receive version labels or status text; the worker sends assigned paragraphs only.
import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../../research-analysis-20260919/icaart/',import.meta.url);
const m=JSON.parse(await readFile(new URL('stimuli-scope-20260920/generated/materials.json',root),'utf8'));
const v=JSON.parse(await readFile(new URL('../stimuli-v8/versions.json',import.meta.url),'utf8'));
const plain=JSON.parse(await readFile(new URL('../stimuli-v8/plain_text_v8.json',import.meta.url),'utf8'));
const excerpts=JSON.parse(await readFile(new URL('stimuli-v4-20260921/excerpts/excerpts.json',root),'utf8'));
const splitSentences=(text,max=230)=>{const parts=[];let cur='';for(const seg of String(text).split(/(?<=。)/)){if(cur&&[...cur].length+[...seg].length>max){parts.push(cur);cur=seg}else cur+=seg}if(cur)parts.push(cur);return parts};
const CONDITIONS=v.conditions; // v8: baseline, missing_info, off_focus, source_deviation
const cases=m.cases.map(c=>{
  const vc=v.cases[c.id];if(!vc)throw new Error('versions missing for '+c.id);const pc=plain.cases[c.id];if(!pc)throw new Error('plain text missing for '+c.id);
  const versions={};for(const k of CONDITIONS){const x=vc.versions[k];versions[k]=x?{paragraphs:x.paragraphs,chars:x.chars,sha256:x.sha256,changed_paragraphs:x.changed_paragraphs,status:v.review_status||'',provenance:x.provenance||null}:null}
  return {id:c.id,domain:pc.domain||c.domain,originalDomain:c.domain,title:c.title,decision:c.decision,
    role:pc.role||c.role,originalRole:c.role,
    request:{title:plain.common.requestTitle,lead:plain.common.requestLead.replace('{role}',pc.role||c.role),paragraphs:pc.request},originalRequest:c.request,
    terms:pc.terms,originalTerms:c.terms,
    sources:c.facts.map((text,i)=>{const ex=excerpts[c.id]?.['S'+(i+1)];if(!ex)throw new Error('excerpt missing '+c.id+' S'+(i+1));return {id:'S'+(i+1),title:`資料 S${i+1}`,paragraphs:[text],excerpt:splitSentences(ex),excerptChars:[...ex].length}}),sourceOrigins:c.origins,sourceDocument:excerpts[c.id]?.source||null,
    handoff:plain.common.handoff,
    fmc:pc.fmc,
    draftTitle:c.title+'に関する報告案',
    understanding:{explanation:plain.explanationTemplate.replace('{a1}',pc.aspects[0]).replace('{a2}',pc.aspects[1]),application:pc.application},originalUnderstanding:c.understanding,
    bases:[{id:'B1',origin:`${v.base_series}: ${vc.base_file}`,judgment_unit:vc.judgment_unit,versions}]};
});
const out={version:'cases-20260924-v8',builtAt:new Date().toISOString(),source:'materials '+m.common.version+' + '+v.version+' + '+plain.version,
  conditions:CONDITIONS,
  common:{notice:plain.common.notice,role:plain.common.role,
    workRule:plain.common.workRule,
    readInstruction:plain.common.readInstruction,
    editInstruction:plain.common.editInstruction,
    disclosure:m.common.disclosure,
    precheck:plain.common.precheck,
    auditNotice:plain.common.auditNotice,readGateNote:plain.common.readGateNote,
    fmcOptions:plain.common.fmcOptions,fmcKeyed:plain.common.fmcKeyed,fmcInstruction:plain.common.fmcInstruction,conditionSpec:plain.common.conditionSpec,
    understandingScale:m.common.understanding_scale},
  cases};
await writeFile(new URL('../src/cases.js',import.meta.url),'/* Generated by tools/build-cases.mjs. Do not edit by hand. */\nexport default '+JSON.stringify(out,null,1)+';\n');
console.log(JSON.stringify({cases:cases.map(c=>({id:c.id,available:CONDITIONS.filter(k=>c.bases[0].versions[k])}))}));
